from datetime import datetime
from typing import Protocol
from uuid import UUID

from app.domain.auth_session import AuthSession
from app.domain.user import User


class UserRepository(Protocol):
    async def create(self, email: str, password_hash: str) -> User: ...

    async def get_by_email(self, email: str) -> User | None: ...

    async def get_by_id(self, user_id: UUID) -> User | None: ...

    async def delete(self, user_id: UUID) -> bool: ...

    async def create_refresh_token(
        self, user_id: UUID, token_hash: str, expires_at: "datetime"
    ) -> UUID: ...

    async def consume_refresh_token(self, token_hash: str) -> User | None: ...

    async def revoke_refresh_token(self, token_hash: str) -> bool: ...

    async def list_active_sessions(self, user_id: UUID) -> list[AuthSession]: ...

    async def is_session_active(self, user_id: UUID, session_id: UUID) -> bool: ...

    async def revoke_other_sessions(self, user_id: UUID, current_session_id: UUID) -> int: ...

    async def set_email_verified(self, user_id: UUID) -> User | None: ...

    async def update_password(self, user_id: UUID, password_hash: str) -> bool: ...

    async def create_action_token(
        self, user_id: UUID, purpose: str, token_hash: str, expires_at: datetime
    ) -> None: ...

    async def consume_action_token(self, purpose: str, token_hash: str) -> User | None: ...

    async def record_security_event(
        self, event_type: str, subject_hash: str, succeeded: bool
    ) -> None: ...
